services:
  css-snippet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ${PROJECT}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
<<<<<<< Updated upstream
=======
    volumes:
      - ./${PROJECT}:/app/${PROJECT}
      
>>>>>>> Stashed changes
